# 1. Choisir une image de base
FROM python:3.10-slim

# 2. Définir le dossier de travail
WORKDIR /app

# 3. Copier et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copier ton code et fichiers statiques
COPY . .

# 5. Exposer le port FastAPI
EXPOSE 8000

# 6. Lancer l'API avec Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
ENV HF_HOME=/app/.cache/huggingface
RUN mkdir -p /app/.cache/huggingface && chmod -R 777 /app/.cache/huggingface

# Création du répertoire de cache
RUN mkdir -p /app/cache
